### ISSUE TITLE
name 'Progressbar' is not defined

### ISSUE THREAD

**Issue by joseph-tharwat** [Roshanpaswan/tkPDFViewer#8]
I write your code and get an error
the error is :
     This error occured while importing neccesary modules or library No module named 'frontend'
Traceback (most recent call last):
  File "C:\Users\jotha\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Programe_Project/python/pdfPreview/pdfPreview.py", line 33, in <module>
    variable2 = variable1.pdf_view(root,pdf_location=r"location",width=50,height=100)
  File "C:\Users\jotha\AppData\Local\Programs\Python\Python310\lib\site-packages\tkPDFViewer\tkPDFViewer.py", line 31, in pdf_view
    loading = Progressbar(self.frame,orient= HORIZONTAL,length=100,mode='determinate')
NameError: name 'Progressbar' is not defined
............................................................................................
I installed all Dependencies

**Comment by Lightwave234** [comment]
what you can do is delete fitz from python, however, though it helps with Progressbar, it does not help with some of the other items in the module that are relient on fitz
